### ISSUE TITLE
PHP8: nie działa quicksearch

### ISSUE THREAD

**Issue by interduo** [chilek/lms#2190]
**Opis błędu**
Brak wyników po wpisaniu czegokolwiek w jakikolwiek quicksearch gdy używamy PHP8.0.

```
[Sat Dec  4 11:24:42 2021] 172.20.2.42:34406 [200]: GET /?m=quicksearch&api=1&ajax=1&mode=customer&what=CD
[Sat Dec  4 11:24:42 2021] PHP Fatal error:  Uncaught TypeError: pg_close(): supplied resource is not a valid PostgreSQL link resource in /home/jkl/PhpstormProjects/lms/lib/LMSDB_driver_postgres.class.php:131
Stack trace:
#0 /home/jkl/PhpstormProjects/lms/lib/LMSDB_driver_postgres.class.php(131): pg_close()
#1 /home/jkl/PhpstormProjects/lms/lib/LMSDB_driver_postgres.class.php(120): LMSDB_driver_postgres->_driver_disconnect()
#2 [internal function]: LMSDB_driver_postgres->_driver_shutdown()
#3 {main}
  thrown in /home/jkl/PhpstormProjects/lms/lib/LMSDB_driver_postgres.class.php on line 131
[Sat Dec  4 11:24:42 2021] 172.20.2.42:34406 Closing
```
Na PHP 7.x działa poprawnie.

**Comment by chilek** [comment]
Widać z PHP 8.0 z jakiegoś powodu nie łączy Ci się z Postgresem i dlatego potem jest błąd zamknięcia połączenia z bazą w funkcji `pg_close()`.

**Comment by interduo** [comment]
Problem zauważam tylko tutaj i tylko w PHP 8.x.

**Comment by interduo** [comment]
U Ciebie na PHP 8.x działa dobrze?

**Comment by interduo** [comment]
`{customerlist}` również nie działa w ogóle na PHP 8.x

**Comment by interduo** [comment]
Jeśli zakomentuje się tą linię w https://github.com/interduo/lms/blob/master/lib/LMSDB_driver_postgres.class.php#L131 to działa.
